---
name: Build and Publish Package
on:
  push:
    branches:
      - "master"
      - "prerelease"
permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write
  id-token: write
  attestations: write
jobs:
  build:
    uses: aps831/workflows/.github/workflows/build-and-publish-nodejs-in-docker-directory-artifact-v2.yaml@refactor/test-output
    # uses: aps831/workflows/.github/workflows/build-and-publish-nodejs-on-runner-package-artifact.yaml@master
    with:
      dockerfile: Dockerfile
      volumes: ".:/app"
      build-command: "npm run-script full"
      templated-files: README.tpl.md
      # build-script: npm install && npm run-script build && npm run-script sbom
      # node-version: "20"
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
