---
name: Build and Publish Package
on:
  push:
    branches:
      - "master"
      - "prerelease"
  pull_request: {}
jobs:
  build:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: read
    uses: aps831/workflows/.github/workflows/publish-nodejs-in-docker-directory-artifact.yaml@refactor/build-release
    with:
      prerelease-branch: "prerelease"
      update-branch-base: "chore/publish-update"
      tag-prefix: "v"
      templated-files: |
        README.tpl.md
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
