---
name: Build and Publish Package
on:
  push:
    branches:
      - "master"
      - "prerelease"
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  build:
    uses: aps831/workflows/.github/workflows/build-and-publish-nodejs-in-docker-directory-artifact.yaml@feat/npm-attestation # TODO
    with:
      templated-files: |
        README.tpl.md
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
