---
name: Build and Publish Package
on:
  push:
    branches:
      - "master"
      - "prerelease"
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  build:
    # uses: aps831/workflows/.github/workflows/build-and-publish-nodejs-in-docker-directory-artifact.yaml@master
    uses: aps831/workflows/.github/workflows/build-and-publish-nodejs-on-runner-package-artifact.yaml@feat/npm-attestation # TODO
    with:
      templated-files: README.tpl.md
      build-script: npm run-script build
      node-version: "20"
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
