---
name: Build and Publish Package
on:
  # push:
  #   branches:
  #     - "master"
  #     - "prerelease"
  pull_request: {}
  issue_comment:
    types:
      - created
jobs:
  build:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: read
    uses: aps831/workflows/.github/workflows/publish-nodejs-in-docker-directory-artifact.yaml@refactor/build-release
    with:
      branch-prerelease: "prerelease"
      branch-update-base: "chore/publish-update"
      release-on-default-branch: false
      tag-prefix: "v"
      templated-files: |
        README.tpl.md
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
