---
name: Build and Publish Package
on:
  push:
    branches:
      - "master"
      - "prerelease"
jobs:
  build:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: aps831/workflows/.github/workflows/build-and-publish-nodejs-in-docker-directory-artifact.yaml@master
    with:
      templated-files: |
        README.tpl.md
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
