---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Gitleaks Check
on:
  workflow_dispatch:
  pull_request:
jobs:
  check:
    permissions:
      contents: read
      issues: read
      pull-requests: read
    uses: aps831/workflows/.github/workflows/gitleaks.yaml@master
